/* ----------------  CALCULAR MONTO TOTAL MENSUALIDAD ------------- */
USE COLEGIO
CREATE TRIGGER des_MONTOTOTAL ON DETALLEMENSUALIDAD AFTER INSERT,UPDATE AS
    DECLARE @IDDETALLE AS INT
    SELECT @IDDETALLE = IDDETALLEMENSUALIDAD FROM INSERTED 
    EXEC sp_CalcularMontoTotal @IDDETALLE 
GO

CREATE TRIGGER des_MONTOTOTAL1 ON DETALLEMENSUALIDAD AFTER DELETE AS
    DECLARE @IDDETALLE AS INT
    SELECT @IDDETALLE = IDDETALLEMENSUALIDAD FROM DELETED 
    EXEC sp_CalcularMontoTotal @IDDETALLE 
GO

/* ----------------  ACTUALIZAR OBSERVACION INSCRIPCION ------------- */

CREATE TRIGGER des_OBSINSCRIPCION ON INSCRIPCION AFTER INSERT,UPDATE AS
    DECLARE @CI AS VARCHAR(10)
    DECLARE @IDCURSO AS INT
    DECLARE @IDNIVEL AS INT
    DECLARE @OBS VARCHAR(200)

    SELECT @CI = CI, @IDCURSO = IDCURSO, @IDNIVEL = IDNIVEL, @OBS = OBSERVACIONES FROM INSERTED 
    
    IF @OBS IS NULL
        UPDATE INSCRIPCION SET OBSERVACIONES = 'Inscripción Regular' WHERE CI=@CI AND IDCURSO=@IDCURSO AND IDNIVEL=@IDNIVEL
GO

/* ----------------  ASIGNAR CODIGO ESTUDIANTE AUTOMATICO ------------- */

CREATE TRIGGER des_CODIGOESTUDIANTE ON PERSONA AFTER INSERT,UPDATE AS
    DECLARE @CI VARCHAR(10)
    DECLARE @TIPOE CHAR(1)
    DECLARE @CODEST VARCHAR(9)

    SELECT @CI = CI, @TIPOE = TIPOE FROM INSERTED 
    
    IF @TIPOE = '1' 
    BEGIN
        SELECT @CODEST = 'EST' + RIGHT('000000' + CAST((SELECT COUNT(*) FROM PERSONA WHERE TIPOE='1') AS VARCHAR), 6)
        UPDATE PERSONA SET CODESTUDIANTE = @CODEST WHERE CI=@CI
    END
GO

/* ----------------  ASIGNAR CODIGO MAESTRO AUTOMATICO ------------- */

CREATE TRIGGER des_CODIGOMAESTRO ON PERSONA AFTER INSERT,UPDATE AS
    DECLARE @CI VARCHAR(10)
    DECLARE @TIPOM CHAR(1)
    DECLARE @CODMAE VARCHAR(4)

    SELECT @CI = CI, @TIPOM = TIPOM FROM INSERTED 
    
    IF @TIPOM = '1' 
    BEGIN
        SELECT @CODMAE = 'PROF' + RIGHT('000' + CAST((SELECT COUNT(*) FROM PERSONA WHERE TIPOM='1') AS VARCHAR), 3)
        UPDATE PERSONA SET CODMAESTRO = @CODMAE WHERE CI=@CI
    END
GO

/* ----------------  VALIDAR FECHAS GESTION ------------- */

CREATE TRIGGER des_FECHASGESTION ON GESTION AFTER INSERT,UPDATE AS
    DECLARE @FECHAINI DATE
    DECLARE @FECHAFIN DATE
    DECLARE @IDGEST INT

    SELECT @IDGEST = IDGESTION, @FECHAINI = FECHAApertura, @FECHAFIN = FECHACierre FROM INSERTED 
    
    IF @FECHAFIN <= @FECHAINI
    BEGIN
        RAISERROR('La fecha de cierre debe ser posterior a la fecha de apertura', 16, 1)
        ROLLBACK TRANSACTION
    END
GO

/* ----------------  ACTUALIZAR ESTADO MATERIA ASIGNADA ------------- */

CREATE TRIGGER des_ESTADOMATERIA ON MAESTROMATER AFTER INSERT AS
    DECLARE @IDMATERIA INT

    SELECT @IDMATERIA = IDMATERIA FROM INSERTED 
    
    UPDATE MATERIA SET DESCRIPCION = DESCRIPCION + ' - Asignada' 
    WHERE IDMATERIA=@IDMATERIA
GO

CREATE TRIGGER des_ESTADOMATERIA1 ON MAESTROMATER AFTER DELETE AS
    DECLARE @IDMATERIA INT

    SELECT @IDMATERIA = IDMATERIA FROM DELETED 
    
    UPDATE MATERIA SET DESCRIPCION = REPLACE(DESCRIPCION, ' - Asignada', '') 
    WHERE IDMATERIA=@IDMATERIA
GO

/* ----------------  CONTROL PORCENTAJE BECA ------------- */

CREATE TRIGGER des_PORCENTAJEBECA ON BECA AFTER INSERT,UPDATE AS
    DECLARE @PORC INT
    DECLARE @CODBECA INT

    SELECT @CODBECA = CODBECA, @PORC = PORCENTAJE FROM INSERTED 
    
    IF @PORC < 0 OR @PORC > 100
    BEGIN
        RAISERROR('El porcentaje de beca debe estar entre 0 y 100', 16, 1)
        ROLLBACK TRANSACTION
    END
GO

/* ----------------  ACTUALIZAR OBSERVACION MENSUALIDAD ------------- */

CREATE TRIGGER des_OBSMENSUALIDAD ON MENSUALIDAD AFTER INSERT,UPDATE AS
    DECLARE @IDMENSUALIDAD INT
    DECLARE @OBS VARCHAR(200)
    DECLARE @TIPOPAGO CHAR(1)

    SELECT @IDMENSUALIDAD = IDMENSUALIDAD, @OBS = OBSERVACION, @TIPOPAGO = TIPOPAGO FROM INSERTED 
    
    IF @OBS IS NULL
    BEGIN
        IF @TIPOPAGO = 'E'
            UPDATE MENSUALIDAD SET OBSERVACION = 'Pago en Efectivo' WHERE IDMENSUALIDAD=@IDMENSUALIDAD
        ELSE IF @TIPOPAGO = 'Q'
            UPDATE MENSUALIDAD SET OBSERVACION = 'Pago con QR' WHERE IDMENSUALIDAD=@IDMENSUALIDAD
    END
GO
